openapi: 3.0.4
info:
  title: Team Dynamics Entropy Service
  description: |-
    API to calculate and fetch entropy of a VR session
  version: 0.0.1
paths:
  /entropy:
    parameters:
      - name: sessionId
        in: query
        required: false
        schema:
          type: integer
      - name: scenarioId
        in: query
        required: false
        schema:
          type: integer
      - name: pertubationId
        in: query
        required: false
        schema:
          type: integer
      - name: from
        in: query
        required: false
        schema:
          type: integer
      - name: to
        in: query
        required: false
        schema:
          type: integer
      - name: time
        in: query
        required: false
        schema:
          type: integer
    get:
      tags:
        - entropy
      summary: |
        Fetch entropy for an entire session

      description: |
        Valid parameter combinations:
        - sessionId (entire session)
        - sessionId + scenarioId (scenario within session)
        - sessionId + from + to (time window)
        - sessionId + time (specific timestamp)
        - sessionId + pertubationId (specific perturbation)
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Entropy"
        "400":
          description: |
            - Invalid session ID supplied
            - Missing session ID
        "404":
          description: session ID not found
        "500":
          description: Server Error

  /session:
    get:
      tags:
        - metadata
      summary: Returns session metadata.
      parameters:
        - name: sessionId
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        "400":
          description: Invalid sessionId

  /sessions:
    get:
      tags:
        - metadata
      summary: List all sessions
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sessions"
        "500":
          description: server error

components:
  schemas:
    Entropy:
      type: object
      properties:
        entropy:
          type: array
          items:
            type: number
        lastCalculated:
          type: string
          format: date-time
        sessionId:
          type: integer
        scenarioId:
          type: integer
        perturbationId:
          type: integer
        from:
          type: integer
        to:
          type: integer
        time:
          type: integer
      required:
        - entropy
        - lastCalculated

    Sessions:
      type: object
      properties:
        sessions:
          type: array
          items:
            type: integer

    Session:
      type: object
      properties:
        sessionId:
          type: integer
        scenarios:
          type: array
          items:
            type: integer
        perturbations:
          type: array
          items:
            type: integer
        totalTime:
          type: integer
        trainees:
          type: array
          items:
            type: integer
        createdAt:
          type: string
          format: date-time
